[package]
name = "rust_waver"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.3"
eframe = "0.30.0"
egui_plot = "0.30.0"
num-complex = "0.4.6"
once_cell = "1.20.2"
rustfft = "6.2.0"
tokio = { version = "1.16.1", features = ["full"] }
